### ISSUE TITLE
How can I use ioreg from Cargo?

### ISSUE THREAD

**Issue by russellmcc** [hackndev/zinc#328]
I don't know that cargo is really set up for multi-crate repos like this.  Why aren't independently useful things like ioreg split up into separate repositories so they can be accessed from cargo? 

I suppose it depends on other crates, like VolatileCell, but still, these could again be in their own repos...

**Comment by farcaller** [comment]
The last time I checked there were issues with uploading crates that are used against nightly to crates.io. Is ti still the case? I'm all in to publish ioregs and volatile_cell.

**Comment by mcoffin** [comment]
```toml
[dependencies.ioreg]
git = "https://github.com/hackndev/zinc.git"
path = "ioreg"
```

That will get you ioreg until we beleive it's stable enough to bother publishing to crates.io.
